spring:
  ai:
    openai:
      api-key: NEED_TO_INPUT
custom:
  jwt:
    secretKey: 979797979797pppppaaaarrrrrrrkkkkkkkk11111111111111111111jjjjjjaaaaaaaaeeeeeee313131313131313131ggggggwwwwwwooooooooonnnnnn
  accessToken:
    expirationSeconds: "#{60 * 10}"